- name: Launch database
  docker_container:
    name: database
    image: denila/tp-devops-database:latest
    env:
      POSTGRES_PASSWORD: "{{ db_password }}"
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - name: my-network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python