- name: Launch backend app
  docker_container:
    name: simple-api
    image: denila/tp-devops-simple-api:latest
    env:
      DATABASE_HOST: "{{ db_host }}"
      DATABASE_PASSWORD: "{{ db_password }}"
    networks:
      - name: my-network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python